# Generated by Django 4.0.6 on 2022-09-13 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(default='profile/x22.png', upload_to='profile/')),
                ('bio', models.TextField(default='hi', null=True)),
                ('cod', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileFallow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ManyToManyField(related_name='fallowing', to=settings.AUTH_USER_MODEL)),
                ('myprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
