# Generated by Django 4.0.6 on 2022-10-17 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_profilefallow_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefallow',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
