# Generated by Django 4.1 on 2022-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapeofile',
            name='image',
            field=models.ImageField(blank=True, default='/profile/x22.png', null=True, upload_to='profile/'),
        ),
    ]
