# Generated by Django 4.1 on 2022-08-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_mediapeofile_image_alter_mypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapeofile',
            name='image',
            field=models.ImageField(default='profile/x22.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(blank=True, default='posts/x22.png', null=True, upload_to=''),
        ),
    ]
