# Generated by Django 4.1 on 2022-08-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_mediapeofile_image_alter_mypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(default='posts/x22.png', upload_to='posts/'),
        ),
    ]
