# Generated by Django 4.0.6 on 2022-08-17 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0020_remove_myuser_email_myuser_bio_myuser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapeofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mediapic',
            name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cptions',
        ),
        migrations.DeleteModel(
            name='MediaPeofile',
        ),
        migrations.DeleteModel(
            name='MediaPic',
        ),
    ]
