# Generated by Django 4.0.6 on 2022-08-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_remove_mediapeofile_user_remove_mediapic_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to='polls.myuser'),
        ),
    ]
