# Generated by Django 4.0.6 on 2022-09-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='hi', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cod',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
