# Generated by Django 4.0.6 on 2022-09-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_customuser_bio_alter_customuser_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
