# Generated by Django 4.1 on 2022-09-05 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
