# Generated by Django 4.1 on 2022-09-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_mypost_author_alter_mypost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
