# Generated by Django 4.1 on 2022-09-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_mypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(null=True, upload_to='posts/'),
        ),
    ]
