# Generated by Django 4.0.6 on 2022-09-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
