# Generated by Django 4.0.6 on 2022-09-05 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFallow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallowing', models.ManyToManyField(related_name='fallowing', to=settings.AUTH_USER_MODEL)),
                ('myprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
