# Generated by Django 4.0.6 on 2022-09-05 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_profilefallow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefallow',
            name='fallowing',
            field=models.ManyToManyField(null=True, related_name='fallowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
