# Generated by Django 4.0.6 on 2022-09-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_profilefallow_fallowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefallow',
            old_name='fallowing',
            new_name='following',
        ),
    ]
