# Generated by Django 4.0.6 on 2022-09-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(default='profile/x22.png', null=True, upload_to='posts/'),
        ),
    ]
